home-assistant/service-hub

services/bots/src/discord/commands/integration.ts, services/bots/src/discord/commands/ping.ts, services/bots/src/discord/discord.decorator.ts, services/bots/src/discord/discord.module.ts
https://user-images.githubusercontent.com/15093472/190893449-d7f1434a-c411-4e97-ab93-303c54599082.mp4
=> Add integration command to Discord bot

services/bots/src/github-webhook/github-webhook.model.ts, services/bots/src/github-webhook/github-webhook.service.ts, services/bots/src/github-webhook/handlers/validate-cla.ts
Hopefully the last one before we can switch over
=> Fixes for CLA and github webhook handling

services/bots/src/github-webhook/handlers/validate-cla.ts
When all commits in a PR are from bots (or ignored users)
- Do not attach "cla-signed" label
- Change the commit status text to indicate why the status was a success
Example https://github.com/home-assistant/core/pull/78922
While frenck has now committed in that PR, that was not the case when the "cla-signed" label was added to it.
I consider that a bug.
=> Handle PRs with all commits filtered

services/bots/src/github-webhook/handlers/docs_missing.ts
Would make https://github.com/home-assistant/core/pull/79043 fail
=> Set docs-missing to failure for new-integration/new-platform if no doc PR links

services/bots/src/discord/commands/message.ts
=> Allow mentioning users in messages

services/bots/src/discord/commands/my.ts, services/bots/src/discord/discord.module.ts
=> Add MyCommand to discord bot

services/bots/src/discord/commands/my.ts
https://user-images.githubusercontent.com/15093472/193280909-e5c9f8b7-a76d-49d4-9a58-627cad1f8477.mp4
=> Add modal to handle params for my links

services/bots/src/discord/commands/integration.ts, services/bots/src/discord/commands/my.ts, services/bots/src/discord/discord.module.ts, services/bots/src/discord/services/integration-data.ts, services/bots/src/discord/services/my-redirect-data.ts
Also adds the integration title when config flow my redirect is used
=> Use services for data operations in discord bot

services/bots/src/github-webhook/handlers/validate-cla.ts
<https://github.com/home-assistant/core/pull/79659#issuecomment-1268648623>
<https://api.github.com/repos/home-assistant/core/commits/39ddc37d7676861f511b41530cf00e65dde09726>
=> Ignore github-action@users.noreply.github.com for CLA

services/bots/src/discord/commands/message.ts, services/bots/src/discord/commands/topic.ts, services/bots/src/discord/discord.const.ts, services/bots/src/discord/discord.module.ts
Simple but handy, post the topic/description of a channel.
If there is no topic, the invoker will be informed about that.
=> Add global TopicCommand

services/bots/src/github-webhook/handlers/set_integration.ts, services/bots/src/github-webhook/utils/text_parser.ts, tests/services/bots/github-webhook/handlers/set_integration.spec.ts
ref https://github.com/home-assistant/home-assistant.io/issues/24489
=> Better handle abc.xyz in integration part of doc URL

services/bots/src/github-webhook/github-webhook.const.ts, services/bots/src/github-webhook/github-webhook.module.ts, services/bots/src/github-webhook/handlers/platinum_review.ts, services/bots/src/github-webhook/handlers/quality_scale.ts, services/bots/src/github-webhook/utils/integration.ts
- Adds quality scale labels to integration PRs
- Add handler to fail a platinum integration if a code owner has not approved
=> Quality Scale labels and platinum review enforcer

services/bots/src/discord/commands/components.ts, services/bots/src/discord/discord.module.ts, services/bots/src/discord/services/component-data.ts
=> Add ComponentsCommand

.github/workflows/ci.yml, data/discord/messages/common.yaml, data/discord/messages/esphome.yaml, data/discord/messages/homeassistant.yaml, services/bots/src/discord/commands/common/index.ts, services/bots/src/discord/commands/common/message.ts, services/bots/src/discord/commands/home-assistant/index.ts, services/bots/src/discord/services/common/index.ts, services/bots/src/discord/services/common/message-data.ts
This moves the /message command to common so the code and data can be shared between the servers
=> Restructure messages

services/bots/src/discord/commands/esphome/component.ts, services/bots/src/discord/services/esphome/component-data.ts
For https://github.com/esphome/esphome-docs/pull/2364
=> Adjust component data

services/bots/src/cla-sign/cla-sign.service.ts
Closes https://github.com/home-assistant/home-assistant.io/issues/24563
=> Use new auth strategy for CLA GitHub client

services/bots/src/github-webhook/handlers/code_owners_mention.ts, services/bots/src/github-webhook/handlers/issue_comment_commands/handler.ts
Fixes the format and trigger issues as displayed here https://github.com/home-assistant/core/pull/80732#issuecomment-1287039643
=> Fix format and ignore bots

services/bots/src/github-webhook/handlers/issue_comment_commands/commands.ts
We should unassign all code owners related to the integration, not just the invoker.
=> Adjust unassign command

services/bots/src/discord/commands/home-assistant/integration.ts, services/bots/src/discord/services/home-assistant/integration-data.ts
This adds integration_type to the response, better typing, and adds links to the responses that were missing it
=> Add integration_type

services/bots/src/github-webhook/github-webhook.const.ts, services/bots/src/github-webhook/github-webhook.module.ts, services/bots/src/github-webhook/handlers/intents_language.ts, tests/services/bots/github-webhook/handlers/intents_language.spec.ts
Adds a handler that will add `language: x` and `type: x` to PRs in the `home-assistant/intents` repository.
=> Add SetIntentsLanguage handler

services/bots/src/discord/commands/home-assistant/my.ts
My HA links aren't very obvious that they take you to the right page in your HA install, hopefully this makes it more obvious :)
=> Update the title of my.home-assistant links

data/discord/messages/homeassistant.yaml
=> Add bot message for ChatGPT

services/bots/src/discord/commands/common/info.ts, services/bots/src/discord/discord.const.ts
This allows for better auto-complete for user selection.
=> Adjust user mention DTO

services/bots/src/github-webhook/github-webhook.const.ts, services/bots/src/github-webhook/github-webhook.module.ts, services/bots/src/github-webhook/handlers/review_drafter.ts
This implements the bot logic needed for the upcoming change to PR drafting.
=> Add ReviewDrafter handler

services/bots/src/github-webhook/handlers/review_drafter.ts
`listRequestedReviewers` does not contain users that have requested changes.
=> Get list of requested reviewers from past reviews

services/bots/src/github-webhook/handlers/review_drafter.ts
For some reason, GitHub does not identify some members as members in the webhook payload.
This changes ignores that value and queries the members list directly.
=> Query review author membership

services/bots/src/github-webhook/handlers/issue_comment_commands/const.ts
=> Use lowercase compare between codeowner and invoker

services/bots/src/github-webhook/github-webhook.model.ts, services/bots/src/github-webhook/handlers/review_drafter.ts
Convert the qraphql query into a helper on the context class to make it easier to reuse in other places.
=> Add helper to convert PR to draft

services/bots/src/github-webhook/handlers/review_drafter.ts
~~Needs https://github.com/home-assistant/developers.home-assistant/pull/1693~~
=> Enable ReviewDrafter for all home-assistant repositories

services/bots/src/github-webhook/handlers/platinum_review.ts
This will allow to add this as required on branch protection rules
=> Always add code-owner-approval status regardless of quality scale

data/discord/messages/homeassistant.yaml
Fix a tyop, add a suggestion from Hmoney07 to suggest a non-default paste expiry
=> Adjust HA messages: Suggest longer expiry for dpaste & typo fix

services/bots/src/github-webhook/github-webhook.const.ts
=> Add event entity component

services/bots/src/github-webhook/handlers/validate-cla.ts
Changing this from a comment to a review with `REQUEST_CHANGES` will change the PR to a draft.
=> When CLA is failing create a review with requested changes

services/bots/src/github-webhook/handlers/validate-cla.ts
SSIA
As requested by @agners 
../Frenck
=> Disable CLA for buildroot repo

services/bots/src/discord/commands/common/index.ts, services/bots/src/discord/commands/common/pinned.ts
=> Implement Discord command to list pinned messages

services/bots/src/discord/commands/common/pinned.ts
=> Adjust URL rendering of pinned message contents

tests/services/bots/github-webhook/verify_enabled_handlers.spec.ts
This PR adds tests to verify what webhook handlers will be used for different payloads.
=> Add tests to verify enabled handlers

services/bots/src/github-webhook/github-webhook.const.ts, services/bots/src/github-webhook/handlers/review_drafter.ts, tests/services/bots/github-webhook/verify_enabled_handlers.spec.ts
This will allow running the `ReviewDrafter` plugin in ESPHome repositories.
Related to https://github.com/esphome/esphome-docs/pull/3450
=> Enable the review drafter plugin for ESPHome

package.json, services/bots/src/github-webhook/github-webhook.model.ts, services/bots/src/github-webhook/github-webhook.service.ts, yarn.lock
Adds the recommended plugin to deal with rate limiting <https://github.com/octokit/plugin-throttling.js>
=> Add plugin-throttling to github bot

data/discord/messages/homeassistant.yaml
Former links were pointing to archived channels
=> Change channel link for addon message command

data/discord/messages/homeassistant.yaml
Feature requests go to discussions section, not issues.
=> Correct frontend feature request link

package.json, services/bots/src/github-webhook/github-webhook.model.ts, services/bots/src/github-webhook/github-webhook.service.ts, yarn.lock
Reverts home-assistant/service-hub#232
This does not work for us as we are not using this class directly but extending it.
lets revert for now, and check alternatives later.
=> Revert "Add plugin-throttling to github bot"

data/discord/messages/homeassistant.yaml
- removing padawan message
- changing jedi message to crow message
- removing repost rule in crosspost message (not needed in Discord forums)
- removing old rules and replacing those by the new ones
=> Update discord messages

services/bots/src/github-webhook/handlers/quality_scale.ts
Adding a new label `quality-scale` to all PRs touching the `quality_scale.yaml` file.
=> Add quality-scale label for PRs touching quality_scale.yaml

data/github/issue_context.yaml
Example:
If your issue is related to Shelly generation 1 device, make sure you have configured [CoIoT peer](https://www.home-assistant.io/integrations/shelly/#shelly-device-configuration-generation-1) correctly.
If your issue is related to battery powered Shelly generation 2/3/4 devices, make sure you have configured [Outbound WebSocket](https://www.home-assistant.io/integrations/shelly/#shelly-device-configuration-generation-2-and-3) correctly.
Please enable [Shelly debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging), let it run for 10-15 minutes, and make sure to capture whatever problem you're having in the debug log.
Note: it is better to drag the log file into the comment (which will add it as an attachment) and not copy paste as …
=> Add Shelly to issue_context.yaml

data/discord/messages/homeassistant.yaml
A message to help in directing people to the development channels.
=> Add a canned message for how to access the discord developer channels
