home-assistant/service-hub

services/bots/src/cla-sign/cla-sign.service.ts

INstead of storing a blank value we store null if there is no company name

Use NULL: true when no company_name

---

services/bots/src/github-webhook/github-webhook.const.ts
services/bots/src/github-webhook/handlers/docs_parenting.ts
services/bots/src/github-webhook/handlers/hacktoberfest.ts

This is to match the repositories that currently have probot active.
We can always extend in the future, but that should not be now when switching the source.

Limit docs_parenting and hacktoberfest

---

services/bots/src/github-webhook/github-webhook.const.ts
services/bots/src/github-webhook/handlers/base.ts
services/bots/src/github-webhook/handlers/hacktoberfest.ts
services/bots/src/github-webhook/handlers/month_of_wth.ts
tests/services/bots/github-webhook/handlers/hacktoberfest.spec.ts

Instead of hardcoding these, we check the "repository" part of the webhook payload to determine if we should run or not.
This way a repository only needs to add the "hacktoberfest" topic to enable this handler.
<https://github.com/orgs/home-assistant/repositories?q=hacktoberfest&type=all>

Make hacktoberfest handler dynamic

---

data/discord_messages.yaml
services/bots/src/discord/commands/message.ts

Source <https://raw.githubusercontent.com/awesome-automations/hassbot-data/master/commands.json>

Import all old commands

---

package.json
yarn.lock

Replaced https://github.com/home-assistant/service-hub/pull/72 and https://github.com/home-assistant/service-hub/pull/79

Bump nestjs-pino to 3.1.1

---

services/bots/src/github-webhook/handlers/set_integration.ts

`HomeAssistantRepository.CORE` now returns `home-assistant/core` but here we only want "core"

Use "core" directly

---

services/bots/src/github-webhook/handlers/docs_missing.ts

Since there are a spot to add doc link in the description, it make sense to run this when the PR is edited as well

Run DocsMissing when pull request are edited

---

services/bots/src/github-webhook/handlers/code_owners_mention.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands.ts

When using `[domain]` as the example additional description, replace it with the integration name in codeowners mention

Replace domain with integration

---

services/bots/src/github-webhook/handlers/issue_comment_commands/commands.ts

Sometimes issues are closed by mistake.
This adds a `reopen` command that can be used by code owners to reopen issues.

Add reopen command

---

services/bots/src/github-webhook/handlers/platinum_review.ts

In the webhook payload that triggers on pull request review, the state is lowercase.
But in the API it's uppercase https://api.github.com/repos/home-assistant/core/pulls/81278/reviews
This PR changes the logic to match with uppercase.

Use uppecase for approved state match

---

services/bots/src/discord/commands/home-assistant/integration.ts
services/bots/src/discord/services/home-assistant/integration-data.ts

Adding the descriptions which I PRed into the HA integrations into the `/integration` command in the bot. It's slightly more informational and helpful to new users to have a description without needing to click a link :)
P.S. sorry about the trailing line breaks being removed, I did make sure Prettier and ESLint were configured though.

Add the description to the integrations in home assistant bot

---

services/bots/src/github-webhook/handlers/platinum_review.ts

Ref: https://github.com/home-assistant/core/pull/81783
This makes sure we do not set failing status on PRs that contain multiple integrations.
Later we would want to expand on this handler to check that _all_ platinum integrations in a PR are approved by a code owner of that integration.

Ignore PRs with multiple integrations for platinum review

---

services/bots/src/cla-sign/cla-sign.controller.ts
services/bots/src/cla-sign/cla-sign.service.ts

Rethrow expected errors as HTTP Bad request, that way the messages can be shown to the user after this https://github.com/home-assistant/home-assistant.io/pull/25496

Throw http exception for request errors in cla sign

---

data/discord/messages/common.yaml

It errantly tells the user to press `Enter` to add a new line, but the default Discord settings require `Shift+Enter`.

Fix Discord message for formatting code

---

services/bots/src/discord/commands/common/message.ts
services/bots/src/discord/services/common/message-data.ts

This allow us to define `fields` for embed messages.

Allow fields in messages

---

services/bots/src/github-webhook/handlers/dependency_bump.ts

- 'setup.py' does not exist anymore.
- 'manifest.json' will not change without the others also changing if its really a dependency-bump.
Replaces #146 
Closes #135

Remove files for dependency_bump handler

---

services/bots/src/github-webhook/handlers/validate-cla.ts

Prefix logins with `@` so users are tagged.
@ludeeus vs ludeeus

Tag users in pullRequestComment

---

services/bots/src/github-webhook/handlers/review_drafter.ts

<https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review>
> author_associationstring Required
How the author is associated with the repository.
> Can be one of: COLLABORATOR, CONTRIBUTOR, FIRST_TIMER, FIRST_TIME_CONTRIBUTOR, MANNEQUIN, MEMBER, NONE, OWNER

Add author_association filter

---

services/bots/src/github-webhook/handlers/code_owners_mention.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/close.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/rename.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/reopen.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/unassign.ts

Currently, we always use "Issue". This makes it better fit the context.

Use the proper type in code owner command descriptions

---

services/bots/src/github-webhook/github-webhook.module.ts
services/bots/src/github-webhook/handlers/new_integrations.ts

Adds logic to the bot to enforce our requirement of a single platform when adding new integrations.

Add NewIntegrationsHandler

---

tests/services/bots/github-webhook/utils/parse_path.spec.ts

I initially added this because I was extending it to include translations. Those are now removed, but the base of the tests still make sense to include

Add base tests for ParsedPath

---

.github/workflows/ci.yml

This is replaced by adding `with.cache: 'yarn'` on the `actions/setup-node` actions

Remove actions/cache

---

services/bots/src/github-webhook/handlers/docs_target_branch.ts

Branches that always will be wrong (like `new`) we should not run against.

Add concept of ignored branches for DocsTargetBranch handler

---

services/bots/src/github-webhook/handlers/validate-cla.ts

`commit.author` can be `null` or an empty object.

Fix check for no commit author

---

services/bots/src/github-webhook/handlers/platinum_review.ts

The `expandOrganizationTeams` helper returns a list of forced lowercase users.
We need to force lowercase to check it.

Force lowercase when checking reviewer

---

webpack.config.js
webpack.config.js 

Apparently, the old file was called `webpack.config.js ` instead of `webpack.config.js`. That tiny space messed up my git.

Change name to file without space

---

services/bots/src/cla-sign/cla-sign.controller.ts
services/bots/src/cla-sign/cla-sign.service.ts
services/bots/src/config.ts

Deployments update: https://github.com/home-assistant/deployments/pull/73

Add authorize handler to CLA bot

---

services/bots/src/github-webhook/github-webhook.const.ts
services/bots/src/github-webhook/github-webhook.module.ts
services/bots/src/github-webhook/handlers/merge_conflict.ts
tests/services/bots/github-webhook/handlers/merge_conflict.spec.ts

While this is intended for the entire org, it's limited to core as a start.

Request changes when there is a conflict

---

package.json
services/bots/src/cla-sign/cla-sign.service.ts
services/bots/src/discord/commands/home-assistant/versions.ts
services/bots/src/discord/services/common/message-data.ts
services/bots/src/discord/services/esphome/component-data.ts
services/bots/src/discord/services/home-assistant/integration-data.ts
services/bots/src/discord/services/home-assistant/my-redirect-data.ts
services/bots/src/github-webhook/handlers/month_of_wth.ts
services/bots/src/github-webhook/utils/integration.ts
tests/services/bots/github-webhook/handlers/issue_comment_commands.spec.ts
yarn.lock

NodeJS now ships with `fetch` on the global namespace. https://nodejs.org/docs/latest-v20.x/api/globals.html
So, there is no reason to keep this package as a dependency anymore.

Remove node-fetch dependency

---

services/bots/src/github-webhook/handlers/validate-cla.ts

PRs with a lot of commits (100+) <https://github.com/home-assistant/core/pull/81724> would not get the status updated as we only process the first 100 commits returned by the API.

Paginate PR commit listing

---

services/bots/src/github-webhook/handlers/review_drafter.ts

The alternative to this is to check the membership of all reviewers and ignore non-member entries.
But this way while it will "fail" on some reviewers, in total it will be fewer API calls.

Split up API call to re-request reviewer

---

services/bots/src/github-webhook/handlers/code_owners_mention.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/base.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/close.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/label-add.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/label-remove.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/rename.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/reopen.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/commands/unassign.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/const.ts
services/bots/src/github-webhook/handlers/issue_comment_commands/handler.ts
tests/services/bots/github-webhook/handlers/issue_comment_commands.spec.ts
tests/utils/test_context.ts

Implement codeowner commands to add/remove labels

---

data/discord/messages/common.yaml

`Shift` is not required as discord knows not to send the message when the cursor is after a single set of \`\`\`

Remove "Shift+" from code format message

---

tests/services/bots/github-webhook/verify_enabled_handlers.spec.ts

Because of #228, #227 should have gotten this change before merging.
Tests are currently failing <https://github.com/home-assistant/service-hub/actions/runs/7260666997/job/19780264822>

Fix test after early merge

---

package.json
services/bots/src/discord/commands/common/info.ts
services/bots/src/discord/commands/common/message.ts
services/bots/src/discord/commands/common/ping.ts
services/bots/src/discord/commands/common/pinned.ts
services/bots/src/discord/commands/common/topic.ts
services/bots/src/discord/commands/esphome/component.ts
services/bots/src/discord/commands/home-assistant/integration.ts
services/bots/src/discord/commands/home-assistant/my.ts
services/bots/src/discord/commands/home-assistant/versions.ts
services/bots/src/discord/discord.const.ts
services/bots/src/discord/discord.decorator.ts
yarn.lock

Bumps both `@discord-nestjs` packages to the latest versions.
The 5.0.0 of both had breaking changes which are adjusted in this PR.

Bump @discord-nestjs/* packages

---

services/bots/src/github-webhook/github-webhook.service.ts

This event does not contain the base data we need to properly react on in, so it throws currently.
We do not want/need this event, so we can just ignore it and return early.

Add set of ignored events

---

services/bots/src/github-webhook/github-webhook.module.ts
services/bots/src/github-webhook/handlers/blocking_labels.ts
tests/services/bots/github-webhook/handlers/blocking_labels.spec.ts
tests/services/bots/github-webhook/verify_enabled_handlers.spec.ts

This adds a new handler to check for labels that should be blocking.
As a start, this will check for the "awaiting-frontend" label in the home-assistant/core repository only, but the `LabelsToCheck` object can easily be extended to add more repositories and labels later.

Add handler for blocking labels

---

data/discord/messages/homeassistant.yaml

Add details of Z2M's [new device support model](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.0).

Update homeassistant.yaml for Z2M 1.35.0

---

services/bots/src/github-webhook/handlers/docs_parenting.ts

Currently the `updateDocsParentStatus` handler only looks at shortform MD links, like `home-assistant/home-assistant#123`, most people are not using that format.
This PR changes the behavior to also include regular URLs, like `https://github.com/home-assistant/home-assistant.io/pull/123`

Extract all doc links in updateDocsParentStatus

---

services/bots/src/github-webhook/handlers/docs_parenting.ts

`context.scheduleIssueLabel('parent-merged');` would schedule the label to be added with the context that triggered this function to be run.
In this case, that would be core/frontend, but we want this to be added to the docs PR.

Add "parent-merged" to docs PR not the invoker

---

services/bots/src/github-webhook/handlers/month_of_wth.ts

Update the labeling strategy to include category ID 61 for the month of WTH.
* Modify `services/bots/src/github-webhook/handlers/month_of_wth.ts` to update the `WTH_CATEGORY_ID` constant to include both category IDs 56 and 61.
* Modify the `handle` method to check for both category IDs 56 and 61 when labeling PRs with the WTH label.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/home-assistant/service-hub/pull/282?shareId=811d11b8-8e1b-4400-93d8-9b1dd0d50b2c).

Update WTH labeling strategy to include category ID 61

---

services/bots/src/discord/listeners/common/line_count_enforcer.ts
tests/services/bots/discord/listeners/line_count_enforce.spec.ts

Currently, all attachments posted by the discord bot are named "message.txt".
This is not great and results in a lot of not easily identifiable files (generally "message (3566782).txt).
This PR changes the name to be constructed based on who posted and also the message ID.
Before:
After:

Make the attachment filename unique and identifiable

---

Dockerfile
data/github/issue_context.yaml
services/bots/src/github-webhook/github-webhook.module.ts
services/bots/src/github-webhook/handlers/issue_context.ts
tests/services/bots/github-webhook/handlers/issue_context.spec.ts
tests/services/bots/github-webhook/verify_enabled_handlers.spec.ts

Adds a new IssueContext handler.
The file `data/github/issue_context.yaml` can be populated with key-value pairs (in YAML and markdown).
The key should match a label, as that is what will be used as the lookup value.
So, for instance, if the label `integration: demo` is added to an issue, then the text "This is a demo integration." will be added to the same comment that adds integration links and ping code owner.
To this one:

Add IssueContext handler to provide more context when issues are opened

---

data/github/issue_context.yaml

Example comment:
The make and model of your Bluetooth adapter will significantly influence your Bluetooth experience and [connection times](https://www.home-assistant.io/integrations/bluetooth/#improving-connection-times). Be sure to include it in the report, and check if it's on the [high-performance list](https://www.home-assistant.io/integrations/bluetooth/#known-working-high-performance-adapters).
If the adapter fails to set up after restarting Home Assistant or upgrading, it's likely a hardware or OS-level kernel issue. You can resolve most set-up problems by powering down and restarting the system. Rebooting the system is not sufficient without powering it down.
Please enable [Bluetooth debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-lo …

Add Bluetooth to issue_context.yaml

---

data/github/issue_context.yaml

Adds additional reporting info for enphase_envoy issues to the bot.
cc @catsmanac and @bdraco for any additional thoughts on the comment or information that may be useful to collect.

Add Enphase Envoy to issue_context.yaml

---

services/bots/src/github-webhook/handlers/docs_missing.ts
tests/services/bots/github-webhook/handlers/docs_missing.spec.ts

Release PRs are different; we merge the branches and don't have a direct documentation PR for them.
This PR adjust the behavior to prevent a constant check error on those PRs. Added tests.

Skip docs-missing checks for release PRs
